// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWlgMiW8fjedcEpKumLN0Tz6M3Tln8YfU',
    appId: '1:365622856851:web:ffa988cf71444d0a529166',
    messagingSenderId: '365622856851',
    projectId: 'vallabh-trinetra',
    authDomain: 'vallabh-trinetra.firebaseapp.com',
    storageBucket: 'vallabh-trinetra.firebasestorage.app',
    measurementId: 'G-WTTCVXPEB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC30CgpSNKdhid9dbVovHqrgH-pgh-jU38',
    appId: '1:365622856851:android:7fcd0c16b41d8517529166',
    messagingSenderId: '365622856851',
    projectId: 'vallabh-trinetra',
    storageBucket: 'vallabh-trinetra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9tVT3K4D5Tp3yMmBExyLBirtfKA-QFDU',
    appId: '1:365622856851:ios:ed3a649e01dad892529166',
    messagingSenderId: '365622856851',
    projectId: 'vallabh-trinetra',
    storageBucket: 'vallabh-trinetra.firebasestorage.app',
    iosBundleId: 'com.example.trinetraVallabh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9tVT3K4D5Tp3yMmBExyLBirtfKA-QFDU',
    appId: '1:365622856851:ios:ed3a649e01dad892529166',
    messagingSenderId: '365622856851',
    projectId: 'vallabh-trinetra',
    storageBucket: 'vallabh-trinetra.firebasestorage.app',
    iosBundleId: 'com.example.trinetraVallabh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWlgMiW8fjedcEpKumLN0Tz6M3Tln8YfU',
    appId: '1:365622856851:web:5d00a977112901dd529166',
    messagingSenderId: '365622856851',
    projectId: 'vallabh-trinetra',
    authDomain: 'vallabh-trinetra.firebaseapp.com',
    storageBucket: 'vallabh-trinetra.firebasestorage.app',
    measurementId: 'G-6S9GVTMQ58',
  );
}
